language: java

before_script:
- wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
- chmod +x buildJdk8Projects.sh
- chmod +x buildJdk11Projects.sh
- chmod +x install-jdk.sh

jdk:
  - openjdk8
jobs:
  include:
    - stage: ☕ 8
      script:
        - ./buildJdk8Projects.sh
    - stage: ☕ 11
      script:
        - echo $JAVA_HOME
        - jdk_switcher use openjdk11
        - echo $JAVA_HOME

cache:
  directories:
  - $HOME/.m2

notifications:
  email: false
