service: spring-cloud-function-aws

provider:
  name: aws
  runtime: java11
  region: eu-central-1
  profile: serverless-admin

package:
  artifact: target/spring-cloud-function-aws-1.0.0-shaded.jar

functions:
  uppercase:
    handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: uppercaseFunction
      FUNCTION_NAME: uppercaseFunction
  lowercase:
    handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: lowercaseFunction
      FUNCTION_NAME: lowercaseFunction
