spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate: 
        jdbc: 
          lob: 
            non_contextual_creation: true
---
spring:
  profiles: generatesql