name: Build sample Java Maven project

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build and test project
      run: mvn -f github-actions-java-maven/pom.xml clean verify
    - name: Build Docker container
      run: cd github-actions-java-maven && docker build -t de.rieckpil.blog/github-actions-sample .
    - name: Access secrets
      env: 
        SUPER_SECRET: ${{ secrets.SUPER_SECRET }}
      run: echo $SUPER_SECRET
    - name: Push Docker images
      run: echo "Pushing Docker image to Container Registry (e.g. ECR)"
    - name: Deploy application
      run: echo "Deploying application (e.g. Kubernetes)"
